version: 2.1
# I used https://circleci.com/orbs/registry/orb/circleci/node for guidance
orbs:
  node: circleci/node@3.0.1

jobs:
  lint:
    executor: node/default
    steps:
      - checkout
      - node/install-npm
      - node/install-packages:
          app-dir: ~/project/github-search
          cache-path: node_modules
          override-ci-command: npm install
      - persist_to_workspace:
          root: .
          paths:
            - .
      - run: npm run lint
  build:
    docker: 
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world"
workflows:
  lint_my_app:
    jobs:
      - lint